language: java
sudo: false
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
    - "react-frontend/node_modules"
env:
  - NODE_VERSION=12
before_install:
  - nvm install $NODE_VERSION
before_script:
  - mkdir -p src/main/resources/static
  - cd react-frontend
  - npm install
  - npm run build
  - cd ..
  - cp -avr react-frontend/build/. src/main/resources/static
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    on_success: "never"
    on_failure: "never"
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: app-gstspiraea
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
    file: "target/gstspiraea.jar"
